### ISSUE TITLE
Troubleshoot Wallet Connection

### ISSUE THREAD

**Issue by stakersunion** [stakersunion/members#17]
Users reporting errors when using Rabby wallet.

**Comment by benv666** [comment]
Also using frame.sh wallet under Brave browser:
![2024-09-08 09_47_12-DevTools - www stakersunion com_](https://github.com/user-attachments/assets/e7fbc50b-54e2-45b0-94d8-bc953c91de4e)

**Comment by stakersunion** [comment]
This appears to be an issue with Clerk's web3 authentication module. A support request has been submitted for:
1. Improved wallet support
2. Providing more detail in signature request (instead of random string).
