### ISSUE TITLE
Automate eligibility check

### ISSUE THREAD

**Issue by valefar-on-discord** [stakersunion/members#5]
Currently when a user goes through the application flow, they provide a url to an etherscan signature and it is then verified manually.

This can be automated in a similar approach to this python example:

```python
from web3.auto import w3
from eth_account.messages import encode_defunct

sig = "0xsignature"
message = encode_defunct(text="Oath")
address = (w3.eth.account.recover_message(message, signature=sig)).lower()

verify_address_exists_in_list(address)
```

**Comment by valefar-on-discord** [comment]
The user provides the etherscan url [here](https://github.com/stakersunion/members/blob/main/src/components/apply/SignatureForm.js#L37)

Which then calls [`/admin/user/verification`](https://github.com/stakersunion/members/blob/main/src/utils/query/admin/user/verification.js#L23)

[API logic](https://github.com/stakersunion/members/blob/main/src/app/api/user/verification/route.js#L27) 

- Introduce web3 library in backend
- Determine if Oath is available, which I don't believe it is and will need to be added
- Determine if valid address list is available
- Use Oath and user provided signature to determine signer address
- Use valid addresses and lookup signer address. If it exists, happy days. If not, notify user

**Comment by thame** [comment]
2648b2286bdc37211fa27276d932c9291e7375ff
